### ISSUE TITLE
janus_video died when there's too much packet loss

### ISSUE THREAD

**Issue by zazabe** [cargomedia/janus-gateway-rtpbroadcast#83]
How to reproduce it:

- start a Performer session, as usual (add `&debug` to the url to get the debug panel) 
- on the `bulldog` box, use this command:   
  `root@bulldog:/home/vagrant# tc qdisc add dev eth1 root handle 1: netem delay 0ms loss 90%`
- wait a bit (~5min), until the client start to re-establish the `main.video` unit connection
- then remove this `packet-loss` constraint:  
  `tc qdisc del dev eth1 root`
- then, try to refresh the Performer page

My env (provisioned yesterday):
```
vagrant@sk:~$ dpkg -l | grep janus
ii  janus                                    0.0.9.git1.088882-wheezy1          amd64        Janus is an open source, general purpose, WebRTC gateway
ii  janus-gateway-audioroom                  0.0.9-wheezy1                      amd64        Cargomedia propretary Janus Audioroom plugin
ii  janus-gateway-rtpbroadcast               0.0.12-wheezy1                     amd64        Cargomedia propretary Janus RTP broadcast plugin
```

Result:

- the `main.video` unit keep trying to establish a connection with `janus-rtpbroadcast.dev.cargomedia.ch`:

<img width="778" alt="screen shot 2016-04-14 at 14 02 33" src="https://cloud.githubusercontent.com/assets/401598/14519622/460dc936-024a-11e6-8a2f-94bf4d16f9cf.png">

- there's no response from him:

*cm_janus_video logs*
```
{"time":"2016-04-14T07:01:26.814Z","level":"info","message":"Removed stream","streamId":"105e3127-2291-43a6-95de-0f7f20c0c6ed","channelId":"482b147f090ad9b2b30e70b48cfbaf75","channelKey":"58R3gg3CN1GKyaxZNC5MOw__","pluginId":2323942351,"sessionId":4127462380,"connectionId":"3b1cbbf9-e587-48f3-9a65-5870a0e32ae0"}
{"time":"2016-04-14T07:01:26.815Z","level":"info","message":"Removed plugin","pluginId":2323942351,"sessionId":4127462380,"connectionId":"3b1cbbf9-e587-48f3-9a65-5870a0e32ae0"}
{"time":"2016-04-14T07:01:26.816Z","level":"info","message":"Removed session","sessionId":4127462380,"connectionId":"3b1cbbf9-e587-48f3-9a65-5870a0e32ae0"}
{"time":"2016-04-14T07:01:29.674Z","level":"info","message":"Removed connection","connectionId":"3b1cbbf9-e587-48f3-9a65-5870a0e32ae0"}
{"time":"2016-04-14T07:01:29.822Z","level":"info","message":"Removed stream","streamId":"9a2896f4-73ba-4355-8cff-c20d18bdb340","channelId":"482b147f090ad9b2b30e70b48cfbaf75","channelKey":"58R3gg3CN1GKyaxZNC5MOw__","pluginId":1979157660,"sessionId":3273447074,"connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.823Z","level":"info","message":"Removed plugin","pluginId":1979157660,"sessionId":3273447074,"connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.824Z","level":"info","message":"Removed plugin","pluginId":1979157660,"sessionId":3273447074,"connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.824Z","level":"info","message":"Removed session","sessionId":3273447074,"connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.824Z","level":"info","message":"Removed connection","connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.825Z","level":"info","message":"Removed session","sessionId":3273447074,"connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:29.825Z","level":"info","message":"Removed connection","connectionId":"04aab27e-a204-4b45-8245-4bac85ee40f2"}
{"time":"2016-04-14T07:01:30.702Z","level":"info","message":"Added connection","connectionId":"90949aa3-74d7-4ca3-8414-5cfcb9e1dd2a"}
{"time":"2016-04-14T07:01:30.704Z","level":"error","message":"Unexpected proxy error. Closing proxy connection.","error":{"stack":"Error: connect ECONNREFUSED\n    at exports._errnoException (util.js:746:11)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)","message":"connect ECONNREFUSED","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}}
{"time":"2016-04-14T07:01:30.707Z","level":"info","message":"Removed connection","connectionId":"90949aa3-74d7-4ca3-8414-5cfcb9e1dd2a"}
{"time":"2016-04-14T07:01:36.707Z","level":"info","message":"Added connection","connectionId":"e6233f5f-2d1f-4f39-8e10-d00cd7cf9f99"}
{"time":"2016-04-14T07:01:36.710Z","level":"error","message":"Unexpected proxy error. Closing proxy connection.","error":{"stack":"Error: connect ECONNREFUSED\n    at exports._errnoException (util.js:746:11)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)","message":"connect ECONNREFUSED","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}}

then... repeat ECONNREFUSED error
```
*janus_video logs*
```
vagrant@sk:~$ tail /opt/janus-cluster/video/var/log/janus/janus.log -f
[Thu Apr 14 06:01:46 2016] [4121685059] The DTLS handshake has been completed
[Thu Apr 14 06:01:46 2016] WebRTC media is now available
[Thu Apr 14 06:05:27 2016] No WebRTC media anymore
[Thu Apr 14 06:05:27 2016] Detaching handle from JANUS CM video plugin
[Thu Apr 14 06:05:27 2016] [WSS-0x1b02a00] Destroying WebSocket client
[Thu Apr 14 06:05:30 2016] Cleaning up handle 4121685059...
[Thu Apr 14 06:05:30 2016] [4121685059] WebRTC resources freed
[Thu Apr 14 06:05:30 2016] [4121685059] Handle and related resources freed
[Thu Apr 14 06:05:33 2016] [WSS-0x1973000] Destroying WebSocket client
[Thu Apr 14 06:05:33 2016] Timeout expired for session 1381318733...

then... nothing.
```   
*client ws frame*

<img width="819" alt="screen shot 2016-04-14 at 13 25 54" src="https://cloud.githubusercontent.com/assets/401598/14518851/09cf7366-0245-11e6-897f-384091ed3b30.png">

- there's no studio agent log too:   
```
root@bulldog:/home/vagrant# tail -f /var/log/studio-agent/studio-agent.log
I, [2016-04-14T05:50:41.810854 #6300]  INFO -- gstreamer: Pipeline changing to state `GST_STATE_READY`
I, [2016-04-14T05:50:41.810996 #6300]  INFO -- gstreamer: Startup of unit `gstreamer-pipeline`
I, [2016-04-14T05:50:42.315867 #6300]  INFO -- gstreamer: Pipeline changing to state `GST_STATE_PAUSED`
I, [2016-04-14T05:50:42.357686 #6300]  INFO -- gstreamer: Pipeline changing to state `GST_STATE_PLAYING`
I, [2016-04-14T06:05:33.715517 #6287]  INFO -- main: Socket-redis event `stop` received.
I, [2016-04-14T06:05:33.715679 #6287]  INFO -- main: Stopping unit `gstreamer-process`
I, [2016-04-14T06:05:33.715800 #6287]  INFO -- main: Stopping unit `janus-mountpoint`
I, [2016-04-14T06:05:33.716252 #6300]  INFO -- gstreamer: STOPPING (received signal 15)
I, [2016-04-14T06:05:33.748603 #6300]  INFO -- gstreamer: Failure at unit `gstreamer-pipeline` (reason: `Pipeline stopped.`)
I, [2016-04-14T06:05:33.748707 #6300]  INFO -- gstreamer: Stopping unit `gstreamer-pipeline`

then... nothing.
```

Expected:
- `janus-video` should not crash (or should restart automatically)...

Workaround:
- Restarting the `studio-agent` is not solving this issue
- Solved with `sudo /etc/init.d/janus_video restart`  

At the end, it seems that the `janus_video` process crashed:
```
vagrant@sk:~$ ps aux | grep janus | grep video
cm-janus  7329  0.1  2.5 689776 104084 ?       Sl   05:49   0:04 /usr/bin/node /usr/bin/cm-janus -c /opt/cm-janus-cluster/video/etc/cm-janus/config.yaml

vagrant@sk:~$ sudo /etc/init.d/janus_video restart
[....] Stopping janus_video: janus_videoNo process in pidfile '/var/run/janus_video.pid' found running; none killed.
. ok
[ ok ] Starting janus_video: janus_video.

vagrant@sk:~$ ps aux | grep janus | grep video
cm-janus  7329  0.1  2.5 689540 104328 ?       Sl   05:49   0:04 /usr/bin/node /usr/bin/cm-janus -c /opt/cm-janus-cluster/video/etc/cm-janus/config.yaml
janus    11144  0.1  0.1 223656  5924 ?        Sl   06:46   0:00 /usr/bin/janus -o -C /opt/janus-cluster/video/etc/janus/janus.cfg -L /opt/janus-cluster/video/var/log/janus/janus.log -F /opt/janus-cluster/video/etc/janus
```

**Comment by kris-lab** [comment]
Did you try to restart `cm-janus` first then `janus`? In general agree there is something no OK. However `janus` log look ok.

**Comment by zazabe** [comment]
I didn't, but the `cm-janus-video` is still running and can't connect to `janus_video` (`{..."level":"error","message":"Unexpected proxy error. Closing proxy connection.","error":{"stack":"Error: connect ECONNREFUSED..."`).

Also, the `janus_video` process is not present before restarting it, which is producing this warning: `No process in pidfile '/var/run/janus_video.pid' found running; none killed.`.

**Comment by zazabe** [comment]
I've opened an issue on cm-janus too, because i don't think we should keep the client like that when our services are down: https://github.com/cargomedia/cm-janus/issues/249

**Comment by zazabe** [comment]
@kris-lab do we have some kind of process supervisor in production to restart janus services automatically when they are down? Should we have one on our box too?

**Comment by njam** [comment]
Yes we have "monit" on production, let's add it also on dev -> https://github.com/cargomedia/sk/issues/3231

If this rtpbroadcast dying problem can be reproduced reliably, then let's try to fix it!

**Comment by zazabe** [comment]
reproduced 5 times this morning (same way than explained above)...

**Comment by zazabe** [comment]
@kris-lab fyi, since I use the latest janus version (sk box pulled/provisioned yesterday), the `janus_video` service is crashing often and without throttling the connection... usually when i reload the performer page...

I'll keep tailing the  `janus_video` log on my terminal and report here if I catch something....

**Comment by njam** [comment]
@zazabe could you provide the last few lines from janus' log when it dies?
See also: https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/85

**Comment by kris-lab** [comment]
I have asked @zazabe to run janus manually with `-d 5`

**Comment by zazabe** [comment]
About this specific issue (throttled connection, the only one I can reproduce), I tried to run janus with `-d 7`, it dies with these logs at the end:

```
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2916
[Thu Apr 14 14:38:36 2016] [3109276211]   >> >> Scheduling 2916 for retransmission due to NACK
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2917
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2918
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2919
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2920
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2922
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2923
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2924
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2925
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2926
[Thu Apr 14 14:38:36 2016] [3109276211]   >> >> Scheduling 2926 for retransmission due to NACK
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2927
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2928
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2929
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2930
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2931
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2932
[Thu Apr 14 14:38:36 2016] [ice.c:janus_ice_cb_nice_recv:1911] [3109276211]   >> 2933
[Thu Apr 14 14:38:36 2016] Got REMB bitrate 50017
[Thu Apr 14 14:38:36 2016] REMB for this PeerConnection: 50017
[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2886

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2890

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2892

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2893

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2895

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2898

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2908

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2916

[Thu Apr 14 14:38:36 2016] [3109276211] ... Retransmitting seq.nr 2926
```

and with the exit code `139`...


full log available here: http://termbin.com/rzrs

**Comment by zazabe** [comment]
hum... this termbin.com is quite limited... the file is here https://www.dropbox.com/s/wxuefdx7u0g132w/janus_video?dl=0

**Comment by kris-lab** [comment]
Thanks for log!

So it happens in the `ICE` in the janus core here https://github.com/meetecho/janus-gateway/blob/master/ice.c#L3149

Agree it should not kill janus, there must be a bug.

**Comment by kris-lab** [comment]
Many people has problem with `libnice` under janus code.

Maybe we could add more debugging with:
```
-l, --libnice-debug           Whether to enable libnice debugging or not  
                              (default=off)
```

Some potentially related problems:
- https://github.com/meetecho/janus-gateway/search?q=libnice&type=Issues&utf8=%E2%9C%93
- https://github.com/meetecho/janus-gateway/issues/503
- https://github.com/meetecho/janus-gateway/issues/370
- https://github.com/meetecho/janus-gateway/issues/315 (same STUN and TURN server problem)

**Comment by kris-lab** [comment]
@zazabe does it still happen to you? with the newest plugin or master?

**Comment by zazabe** [comment]
Seems fixed, `janus_video` is still alive ;)

btw, now i get other issues on the client side:

<img width="1102" alt="screen shot 2016-05-03 at 18 28 41" src="https://cloud.githubusercontent.com/assets/401598/14982020/5ca213ce-115d-11e6-8a1e-7e0e11e98547.png">

then

<img width="954" alt="screen shot 2016-05-03 at 18 30 38" src="https://cloud.githubusercontent.com/assets/401598/14982021/5ca5eaa8-115d-11e6-924b-aba80df69793.png">

then everything is working fine again if i remove the throttling, without reloading the page, so i suppose it's expected if the connection to bulldog is too bad, @njam wdyt?

**Comment by njam** [comment]
So you filtered the connection of bulldog, and of performer?

Many things can happen in such a scenario. If either of these clients loses the WebSocket connection some resources will destroyed, and CM will spit errors. 

I think it's expected/okay.

**Comment by kris-lab** [comment]
Agree, many things can happen.

**Comment by zazabe** [comment]
ok, let's close this issue!
